### ISSUE TITLE
Shell Starter

### ISSUE THREAD

**Issue by Hearen** [Hearen/Linux-scripts#3]

**Comment by Hearen** [comment]
## Auto-generate deployment scripts for existed OPT environments

Since it's inapplicable to get the latest repo: git@scm.hue.workslan:operation-tool/operation-tool-deploy-script.git via following three methods: 

1. Work Terminal in IR to SCM is not connected;
2. Jenkins to IR Work Terminal is not connected;
3. RC in IR to SCM is not connected;

Once these three conditions still stands, the solutions below will be effective. 

### 1. Get the latest version

In the local computer, we get the latest repo:

#### tar

Download the `tar` at: [https://scm.hue.workslan/operation-tool/operation-tool-deploy-script/tree/develop](https://scm.hue.workslan/operation-tool/operation-tool-deploy-script/tree/develop)

#### git repo

or 

```
cd /tmp/ && mkdir -p script-generator && cd script-generator &&  git clone git@scm.hue.workslan:operation-tool/operation-tool-deploy-script.git
```

If encounter `permission` issues as (131): 

```
Cloning into 'operation-tool-deploy-script'...
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

Check https://github.com/Hearen/stackoverflow/issues/24


### 2. Locate the latest version

```
ls ~/ansible-multi/ | grep -Eo '[0-9]{2}\.[0-9]{2}\.[0-9]{2}\.[0-9]{4}' | tail -n 1

```

### 3. Copy the main.yml

```
cp ~/ansible-multi/18.07.00.0000/vars/main.yml operation-tool-deploy-script/opt-deploy/vars/main.yml
```


### 4. Copy the pem files

based on the `main.yml`, we need two different pem files: `AWS_WORK_TERMINAL_KEYPAIR` and `AWS_GENERAL_KEYPAIR`; 

**`ansible-*` or `hue-operation-tool-*`.**

#### prepare the keys

```
scp hearen@172.26.143.2:/home/hearen/Documents/pem/hue-operation-tool.pem ~/keys/
scp hearen@172.26.143.2:/home/hearen/Documents/pem/hue-operation-tool-work-terminal.pem ~/keys/
```

copy to `operation-tool-deploy-script/opt-deploy/vars`

```
cd /tmp/script-generator && scp /home/personalize/keys/hue-operation-tool* operation-tool-deploy-script/opt-deploy/vars/
```

### 5. Configure ansible.cfg

```
cd /tmp/script-generator && vim operation-tool-deploy-script/opt-deploy/ansible.cfg
```
paste the following `library` requires an absolute path: 

```
[defaults]
host_key_checking = False
library = /tmp/script-generator/operation-tool-deploy-script/library  
```

### 6. Validate and Fix issues

```
$ operation-tool-deploy-script/opt-deploy/verify-pre-conditions.sh
```

```
[ERROR] operation-tool-deploy-script/opt-deploy/vars/main.yml is different from operation-tool-deploy-script/opt-deploy/vars/main.yml.template.
[ERROR] > LOG_ANALYSIS_INFLUX_INSTANCE_TYPE
> LOG_ANALYSIS_INFLUX_SERVER_IP
> LOG_ANALYSIS_INFLUX_VOLUME_SIZE is not exists at vars/main.yml
[ERROR] Setup is not finished.... Please check log.
```

**Comment by Hearen** [comment]
```
#!/bin/bash

##
# @Author: LHearen@gmail.com or luo_so@worksap.co.jp
# @Date: Wed Oct 24 16:53:28 HKT 2018
# @Description: This script is used to auto-generate the deployment scripts for OPT IR environment.
# @Wiki: https://scm.hue.workslan/operation-tool/resource-controller/issues/8
##

# the name of this script
THIS_SCRIPT_NAME=$(basename "$0")

# to get absolute path for each file and folder
BASE_DIR=$(pwd)

# ansible-multi absolute path
ANSIBLE_MULTI_DIR="$HOME/ansible-multi";

# ToDo: source to generate the final results
# default is along with script in the same directory
DEFAULT_SOURCE_DIR="."

# ToDo: ask to change
DEFAULT_PEM_DIR="~/keys"

# ToDo:
DEFAULT_NEW_VERSION=""


function exitWithMsg() {
    exitCode=$1
    msg=$2
    [[ ! -z "${msg}"  ]] && echo "${msg}" 1>&2
    showHelp;
    exit ${exitCode}
}

function showHelp() {
    echo "*** Sorry for this inconvenience ***";
    echo "Please collect the basic debug info before reaching out for help."
    echo -e "Follow the following commands to collect the debug info.\n"
    echo "****************************************************************************"
    echo "export PS4='(${BASH_SOURCE}:${LINENO}): - [${SHLVL},${BASH_SUBSHELL},$?] $ '"
    echo "bash -x ${THIS_SCRIPT_NAME}";
    echo -e "****************************************************************************\n"
    echo "Now, if you still cannot solve this issue yourself. "
    echo -e "Just contact Hearen@morphling-developer, remember to enclose the debug info please.\n"
    echo -e ":( Sorry :(\n\n\n\n\n";
}

function updateDefaultValue() {
    local defaultValueName=$1
    local hintMsg=$2
    echo "Press <Enter> to use default ${!defaultValueName} or input new below: "
    read newValue
    [[ -z ${newValue} ]] || eval ${defaultValueName}=${newValue}
}


function getLatestValidVersion() {
    ls ${ANSIBLE_MULTI_DIR} | grep -Eo '[0-9]{2}\.[0-9]{2}\.[0-9]{2}\.[0-9]{4}$' | tail -n 1
}

function copyTheMainYml() {
    version=$1
    cp ~/ansible-multi/${version}/vars/main.yml ${BASE_DIR}/operation-tool-deploy-script/opt-deploy/vars/main.yml
    exitWithMsg $? "Copy main.yml failed"
}

function copyPemFiles() {
    cp ${DEFAULT_PEM_DIR} ${BASE_DIR}/operation-tool-deploy-script/opt-deploy/vars/
}

function configureAnsibleCfg() {
    echo "[defaults]" > ${BASE_DIR}/operation-tool-deploy-script/opt-deploy/ansible.cfg
    echo "host_key_checking = False" >> ${BASE_DIR}/operation-tool-deploy-script/opt-deploy/ansible.cfg
    echo "library = ${BASE_DIR}/operation-tool-deploy-script/library" >> ${BASE_DIR}/operation-tool-deploy-script/opt-deploy/ansible.cfg
}

function finalValidate() {
    ${BASE_DIR}/operation-tool-deploy-script/opt-deploy/verify-pre-conditions.sh
    exitWithMsg 1 "Please check the details above."
}


# the entry of the script;
function main() {
    latestValidVersion=$(getLatestValidVersion);
    copyTheMainYml ${latestValidVersion};
    echo ${latestValidVersion}
    echo ${BASE_DIR};
    showHelp;
}

main "${@}";

```

**Comment by Hearen** [comment]
ToDo:
- function used to check commands to be used;
- back up before start to generate;
- rollbackable whenever it is using `exitWithMsg`;


Features:
- generate the deployment scripts based on the latest repository;
- automatically configure all the things you can think of;
- roll back when bad things occur automatically.

**Comment by Hearen** [comment]
#### function - get extension 

```
$ file=/Users/lhearen/programs/hearen.github.io/package.json 
$ file=$(basename -- "$file")
$ echo "${file##*.}"
json
$ echo "${file%.*}"
package
```

https://stackoverflow.com/questions/965053/extract-filename-and-extension-in-bash

**Comment by Hearen** [comment]
#### function - check file timeout

```
if test `find "text.txt" -mmin +120`; then   echo old enough; fi
```

**Comment by Hearen** [comment]
### String comparison

```
# variable to a literal string;
if [ "$s1" = "XYZ" ];


# string variable to string variable;
if [ "$s1" == "$s2" ]


# string contains;
if [[ $s1 == *"$s2"* ]]
```

**Comment by Hearen** [comment]
### Print colorful text
```
red=`tput setaf 1`; green=`tput setaf 2`; reset=`tput sgr0`; echo "${red}red text ${green}green text${reset}";
```
https://stackoverflow.com/questions/5947742/how-to-change-the-output-color-of-echo-in-linux

**Comment by Hearen** [comment]
### Issues

- [x] exit with messages always;
- [x] proper message to indicate the progress;
- [x] emphasize the `SUCCESSFULLY`;
- [x] empty lines and separators to soften the eyes using ` \/ `perhaps;
- [ ] test each core functions;
- [ ] plugin in vim for shell editor;
- [x] using prefix to locate the compressed file;
- [x] updateDefaultValue - add extra message to clarify;
- [x] `environment-config-vars/jill/main.yml` is different from the `main.yml` in jill?
- [ ] track down what changes after `./verify-pre-conditions.sh`;
- [x] clear out first when start;
- [ ] rollback whenever it's stopped;

**Comment by Hearen** [comment]
### Get the latest under a folder

```
ls -lrt ~/Downloads/ | grep operation-tool-deploy-script | tail -n 1
```
